name: Trigger auto deployment for budgetapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/budgetapp-AutoDeployTrigger-bb8fff6e-0516-4383-8050-ac7f8241518d.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: budgetappr1ae0.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USER}}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: budgetappr1ae0.azurecr.io/budget:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n budgetapp -g rg-budgetapp --server budgetappr1ae0.azurecr.io --username  ${{ secrets.BUDGETAPP_REGISTRY_USERNAME }} --password ${{ secrets.BUDGETAPP_REGISTRY_PASSWORD }}
            az containerapp update -n budgetapp -g rg-budgetapp --image budgetappr1ae0.azurecr.io/budget:${{ github.sha }} --debug
